version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - heychat-net

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - heychat-net

networks:
  heychat-net:
    driver: bridge 